spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

jwt:
  secret: h3Qbjyj5kPvN6Pdkggib5fxC2sKWIP5t
  expiration-ms: 86400000 # 1 day